version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    pre_build: null
    commands:
      - npm install
    build:
      commands:
        - npm build
        - npm test
  reports:
    jest_reports:
      files:
        - jestTest
      file-format: JUNITXML
      base-directory: /jestTest
  post_build:
    commands:
      - echo Tests Complete
      - echo Build completed on `date`
  artifacts:
    files:
      - package.json
      - src/*
      - test/*
      - target/npmlist.json
