version: 0.2
      
phases:
  install:
    on-failure: ABORT 
    runtime-versions:
      nodejs: latest
  pre_build:
    on-failure: ABORT 
    commands:
      - npm install
  build:
    on-failure: CONTINUE
    commands:
      - npm test
  post_build:
    on-failure: ABORT
    commands:
      - echo Tests Complete
      - echo Build completed on `date`

artifacts:
  files:
    - package.json
    - src/*
    - test/*
    - target/npmlist.json