version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
     - echo Installing source NPM dependencies...
      - npm install -g jest 
  build:
    commands:
      - echo Running Tests
      - npm test
  post_build:
    commands:
      - echo Tests Complete
      - echo Build completed on `date`
artifacts:
  files:
    - package.json
    - src/* 
    - test/*
    - target/npmlist.json